# permissions for end users to edit route53s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: route53-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pointless-operator
    app.kubernetes.io/part-of: pointless-operator
    app.kubernetes.io/managed-by: kustomize
  name: route53-editor-role
rules:
- apiGroups:
  - cache.jmichaud.net
  resources:
  - route53s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.jmichaud.net
  resources:
  - route53s/status
  verbs:
  - get
